- composer.lock
Fixes issue with code coverage
```sh
PHPUnit 9.5.15 by Sebastian Bergmann and contributors.
Testing 
SebastianBergmann\CodeCoverage\CodeCoverage::append(): Argument #1 ($rawData) must be of type SebastianBergmann\CodeCoverage\Data\RawCodeCoverageData, SebastianBergmann\CodeCoverage\RawCodeCoverageData given.
```
by updating phpunit/php-code-coverage to version 9.2.12.
> TVIST1: Update phpunit/php-code-coverage

- templates/sidebar/case-sidebar.html.twig
* Displays `leaseAddress` rather than `complainantAddress` for `ResidentComplaintBoardCase` and `RentBoardCase`
> Display lease address in side bar

- templates/dashboard/index.html.twig
* Adds counters to dashboard
Before 
After
> TVIST1: Add more counters to dashboard

- src/Form/FenceReviewCaseType.php
- src/Form/PartyFormType.php
- src/Form/RentBoardCaseType.php
- src/Form/ResidentComplaintBoardCaseType.php
- templates/form/theme.html.twig
- templates/party/add.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
* Updates labels on forms to be more clear
Before 
After
https://jira.itkdev.dk/browse/TVIST1-556
> TVIST1-556: Update labels on case and party forms

- config/packages/twig.yaml
- fixtures/agenda_item.yaml
- templates/case/log.html.twig
- templates/case/log_entry_show.html.twig
https://jira.itkdev.dk/browse/TVIST1-604
* Removes twig `date` filter timezone configuration
* Handles `LogEntry` explicitly as it is only occurrence of a `DateTime` object where both the date and time matters.
> TVIST1-604: Removed twig timezone configuration

- assets/party/identifier-lookup.js
- src/Controller/CaseController.php
- src/Service/CaseManager.php
- src/Service/CprHelper.php
- src/Service/CvrHelper.php
- src/Service/IdentificationHelper.php
- templates/case/_case_show/_resident_and_rent_board_shareds.html.twig
- templates/case/_case_show/fence_review_case.html.twig
- templates/case/_identifier.html.twig
- templates/case/_validate_identifier.html.twig
~~Only case parties contain address protection information. I.e. when validating case bringer we should not include the address protection value in data comparison between CPR/CVR register and case data.~~
We do in fact have address protection on bringer/accused. We should just not consider it when dealing with businesses as they cannot be under address protection.
> TVIST1: Fix bringer identification validation

- src/Service/CaseManager.php
* Handles issue where property accessor was called with `null` as property path.
> TVIST1: Avoid calling propertyAccessor with null as propertyPath

- CHANGELOG.md
- src/Service/MailTemplate/ComplexMacroHelper.php
https://jira.itkdev.dk/browse/TVIST1-670
* Changes the layout of the table generated by PHPWord on `agenda.items` macro
* Adds a counter to agenda items on `agenda.items` macro
Before
After
> TVIST1-670: Updated agenda.items macro

- .github/workflows/pr.yaml
- CHANGELOG.md
- src/EventSubscriber/EntityPostPersistSubscriber.php
https://jira.itkdev.dk/browse/TVIST1-721
* Stops TVIST1 sending receipts upon case creation - for now.
> TVIST1-721: Turned off case receipts

- fixtures/digital_post.yml
- src/Command/DigitalPostListCommand.php
- src/Entity/DigitalPost.php
- src/Service/DigitalPostHelper.php
- templates/case/communication/digital_post/index.html.twig
- templates/case/communication/digital_post/show.html.twig
- translations/digital_post+intl-icu.da.xlf
- translations/digital_post+intl-icu.en.xlf
https://jira.itkdev.dk/browse/TVIST1-786
Handles digital post maximum subject length when displaying and sending digital post (the full subject is still stored in the database).
> TVIST1-786: Handled digital post maximum subject length

- CHANGELOG.md
- src/Service/DigitalPostHelper.php
https://jira.itkdev.dk/browse/TVIST1-786
Bumps digital post max subject length to 50, cf. https://docs.kombit.dk/integration/sf1600/2.5/pakke > "SF1600 - Print på Serviceplatformen v.2.5.pdf" > Page 76:
> Titel på dokumentet. Ved for- sendelser til eBoks, må der maksimalt angives 50 tegn.
> TVIST1-786: Bumped subject max length

- CHANGELOG.md
- fixtures/mail_template.yaml
- src/Controller/Admin/MailTemplateCrudController.php
- src/Service/MailTemplateHelper.php
- translations/admin+intl-icu.en.xlf
- translations/admin.da.xlf
https://jira.itkdev.dk/browse/SUPP0RT-874
Handles invalid custom field names.
*Note*: The fields are not validated when defined, but only valid names are used when editing and using the field values.
> SUPP0RT-874: Handle invalid custom field names

- CHANGELOG.md
- src/Service/SF1601/DigitalPoster.php
https://jira.itkdev.dk/browse/TVIST1-436
Removes actual file content from MeMo message before storing in database.
> TVIST1-436: Skipped storing MeMo file content in database

- CHANGELOG.md
- docker-compose.override.yml
- docker-compose.server.override.yml
- docker-compose.server.yml
- docker-compose.yml
Moves custom project docker settings into “override” files (cf. https://docs.docker.com/compose/extends/#adding-and-overriding-configuration).
The “base” files, `docker-compose.server.yml` and `docker-compose.yml`, are exactly the same as the templates in https://github.com/itk-dev/devops_itkdev-docker/tree/develop/templates/symfony-6.
Caveat: We still have a single custom setting in https://github.com/itk-dev/naevnssekretariatet/blob/develop/.docker/vhost.conf#L6-L8 and we/I don't know if we can handle that in a better way.
> TVIST1-755: Custom project docker compose settings in override files

- CHANGELOG.md
- migrations/Version20230330110018.php
- src/Command/DigitalPostEnvelopeListCommand.php
- src/Entity/DigitalPostEnvelope.php
- src/Service/SF1601/DigitalPoster.php
- src/Service/SF1601/ForsendelseHelper.php
https://jira.itkdev.dk/browse/TVIST1-809
- 🐛 fix(DigitalPoster.php): fix null pointer exception when forsendelse is null The code now checks if the forsendelse variable is null before setting the forsendelse and forsendelseUuid properties of the envelope object. This prevents a null pointer exception that would occur when the forsendelse variable is null.
- 🔨 refactor(DigitalPostEnvelope.php): add errors property and methods to handle errors 🔨 refactor(SF1601/DigitalPoster.php): add error to DigitalPostEnvelope when sending digital post fails The DigitalPostEnvelope entity now has an errors property that is used to store errors that occur when sending a digital post. The addError method is used to add an error to the errors property. The getErrors method is used to retrieve the errors …
> TVIST1-809: Digital post fixes

- CHANGELOG.md
- composer.lock
https://jira.itkdev.dk/browse/TVIST1-795
* Downgrades `symfony/maker-bundle` to ensure support for annotations.
https://github.com/symfony/maker-bundle/issues/1152
> TVIST1-795: Downgraded maker-bundle version to support annotations

- CHANGELOG.md
- src/Form/MailTemplateCustomDataType.php
https://jira.itkdev.dk/browse/TVIST1-820
* Properly displays mail template custom data by avoiding overwriting of `$options`.
> TVIST1-820: Properly displays mail template custom data

- CHANGELOG.md
- src/Command/DigitalPostEnvelopeListCommand.php
https://jira.itkdev.dk/browse/TVIST1-826
Adds useful `message-uuid` filter on `tvist1:digital-post-envelope:list` command.
> TVIST1-826: Added `message-uuid` filter on `tvist1:digital-post-envelope:list` command

- CHANGELOG.md
- migrations/Version20230516102033.php
- src/Controller/HearingBriefingController.php
- src/Controller/HearingController.php
- src/Entity/HearingBriefing.php
- src/Entity/HearingBriefingRecipient.php
- templates/case/hearing/briefing/show.html.twig
https://jira.itkdev.dk/browse/TVIST1-840
* Moves attachments from `HearingBriefing` to `HearingBriefingRecipient`
* Adds logic to ensure own hearing letter is not attached to briefing.
> TVIST1-840: Updated hearing briefing logic

- CHANGELOG.md
- README.md
- assets/app.js
https://jira.itkdev.dk/browse/TVIST1-828
* Uses document on 'load' rather than 'ready' to void missing elements
> TVIST1-828: Use document on load rather than ready

- CHANGELOG.md
- src/Command/DigitalPostEnvelopeListCommand.php
https://jira.itkdev.dk/browse/TEAMMANAGE-2784
> TEAMMANAGE-2784: Added digital post id filter on envelope list command

- CHANGELOG.md
- src/Service/MailTemplateHelper.php
https://leantime.itkdev.dk/tickets/showKanban#/tickets/showTicket/1043
Previously, we made it more convenient for users by adding relation data with the 'recipient' prefix. This was not done with hearing briefings (https://github.com/itk-dev/naevnssekretariatet/blob/develop/src/Service/MailTemplateHelper.php#L350-L351)
* Added above mentioned convenience when creating hearing briefings.
**Note:** Test fails due to https://github.com/symfony/symfony/issues/52844 which has been fixed by updating dependencies in develop by https://github.com/itk-dev/naevnssekretariatet/commit/28f88c78e6bbca89e58dd85c6b5dd3c47a5ee5a3, which is yet to be released.
> #1043: Template placeholder convenience

- CHANGELOG.md
- config/packages/security.yaml
- src/Controller/Admin/DashboardController.php
- src/Controller/DefaultController.php
- templates/navbar/_menu.html.twig
- translations/navbar+intl-icu.da.xlf
- translations/navbar+intl-icu.en.xlf
https://leantime.itkdev.dk/#/tickets/showTicket/1234
* Adds logout functionality
> #1234: Added logout functionality

- CHANGELOG.md
- src/Repository/CaseEntityRepository.php
https://leantime.itkdev.dk/#/tickets/showTicket/1479
* Filters out finished cases (i.e. cases with last board status) during agenda case item creation.
> 1479: Filter out finished cases when creating agenda case items

- CHANGELOG.md
- composer.json
- composer.lock
Release 1.6.0
Note: I've checked that the change
``` patch
diff --git a/composer.json b/composer.json
index 7a70a227..03e93a40 100644
--- a/composer.json
+++ b/composer.json
@@ -37,7 +37,7 @@
"itk-dev/beskedfordeler-symfony": "^1.0",
"itk-dev/datafordeler-php-client": "^1.0",
"itk-dev/openid-connect-bundle": "^3.1",
-        "itk-dev/serviceplatformen": "dev-feature/postForespoerg-types",
+        "itk-dev/serviceplatformen": "^1.6",
"knplabs/knp-paginator-bundle": "^5.6",
"league/oauth2-client": "^2.6",
"lexik/form-filter-bundle": "^7.0",
```
does not introduce changes thats haven't been tested by the customer.
> Release 1.6.0
