itk-dev/naevnssekretariatet

- .env
- CHANGELOG.md
https://jira.itkdev.dk/browse/NSEK-104
> NSEK-104: Adding missing database variables to .env file

- docker-compose.yml
https://symfony.com/doc/current/setup/symfony_server.html#docker-integration
> Add symfony cli docker integration

- CHANGELOG.md
- README.md
- docs/TESTING.md
https://jira.itkdev.dk/browse/NSEK-138
> NSEK-138: Updating Cypress to 6.5.0 so same version is used project wide

- templates/case/show.html.twig
- templates/layout-with-submenu.html.twig
- templates/navbar/navbar-menu.html.twig
- templates/navbar/navbar.html.twig
- templates/sidebar/sidebar.html.twig
https://jira.itkdev.dk/browse/NSEK-148
> NSEK-148: Add latest communication and latest notes

- assets/base.js
- assets/base.scss
- package.json
- templates/case/status-info.html.twig
- yarn.lock
https://jira.itkdev.dk/browse/NSEK-150
> NSEK-150: Status info

- templates/case/parties.html.twig
https://jira.itkdev.dk/browse/NSEK-151
> NSEK-151: Add parties markup

- templates/case/communication.html.twig
https://jira.itkdev.dk/browse/NSEK-152
> NSEK-152: Communication

- src/Controller/CaseController.php
- templates/case/documents-create.html.twig
- templates/case/documents.html.twig
https://jira.itkdev.dk/browse/NSEK-153
> NSEK-153: Add documents markup

- assets/base.js
- templates/case/log.html.twig
https://jira.itkdev.dk/browse/NSEK-156
> NSEK-156: Log markup

- templates/case/decision.html.twig
https://jira.itkdev.dk/browse/NSEK-154
> NSEK-154: Add dicision markup

- composer.json
- composer.lock
- symfony.lock
> TVIST1: AliceBundle fork

- src/Entity/CaseEntity.php
> TVIST1-308: Added case toString method

- src/Repository/UserRepository.php
* Fixed `UserRepository` `findByRole` method.
> TVIST1-427: Fix findByRole UserRepository method

- src/Controller/NoteController.php
- templates/case/index.html.twig
- templates/notes/index.html.twig
- templates/notes/new.html.twig
- translations/notes+intl-icu.da.xlf
* Added ability to create note in new window
> TVIST1-426: Allow creation of note in new window

- fixtures/board.yaml
- fixtures/case_entity.yaml
- fixtures/complaint_category.yaml
- migrations/Version20211213102418.php
- src/Controller/CaseController.php
- src/Entity/Embeddable/Address.php
- src/Exception/AddressException.php
- src/Form/Embeddable/AddressType.php
- src/Logging/EntityListener/AbstractEntityListener.php
- src/Logging/EntityListener/CaseListener.php
- src/Service/AddressHelper.php
- templates/case/_address.html.twig
- templates/case/_case_show/_resident_and_rent_board_shareds.html.twig
- templates/case/_case_show/fence_review_case.html.twig
- templates/case/_validate_address.html.twig
- templates/case/show.html.twig
- templates/translations/case.html.twig
- translations/case+intl-icu.da.xlf
https://jira.itkdev.dk/browse/TVIST1-458
- TVIST1-458: Made floor and side optional on Address form
- TVIST1-458: Added Address validation
- TVIST1-458: Added Address validation action
- TVIST1-458: Used AJAX form Address validation
> TVIST1-458: Validate address

- assets/app.js
- assets/app.scss
- assets/case/new.js
- assets/dawa-address-lookup.js
- assets/dawa-address-lookup.scss
- migrations/Version20211215084311.php
- package.json
- src/Entity/Embeddable/Address.php
- src/Form/Embeddable/AddressLookupType.php
- src/Form/Embeddable/AddressType.php
- src/Form/FenceReviewCaseType.php
- src/Form/RentBoardCaseType.php
- src/Form/ResidentComplaintBoardCaseType.php
- templates/case/edit.html.twig
- templates/case/new.html.twig
- webpack.config.js
- yarn.lock
https://jira.itkdev.dk/browse/TVIST1-458
- TVIST1-458: Added DAWA address lookup
> TVIST1-458: Address lookup

- src/Entity/CaseEntity.php
https://jira.itkdev.dk/browse/TVIST1-17
* Added default value to deadlines upon initial creation of case entities
> TVIST1-17: Add default value for case entity deadlines

- assets/app.scss
- assets/content/form.scss
https://jira.itkdev.dk/browse/TVIST1-471
Before
After
> TVIST1-471: Marked required inputs

- composer.json
- composer.lock
- config/services.yaml
- docs/TRANSLATIONS.md
- src/Controller/CaseController.php
- src/Controller/SidebarController.php
- src/Entity/Embeddable/Address.php
- src/Entity/LogEntry.php
- src/Logging/EntityListener/AgendaCaseItemListener.php
- src/Logging/EntityListener/BoardListener.php
- src/Logging/EntityListener/CaseDecisionProposalListener.php
- src/Logging/EntityListener/CaseDocumentRelationListener.php
- src/Logging/EntityListener/CaseListener.php
- src/Logging/EntityListener/CasePartyRelationListener.php
- src/Logging/EntityListener/CasePresentationListener.php
- src/Logging/EntityListener/ComplaintCategoryListener.php
- src/Logging/EntityListener/MunicipalityListener.php
- src/Logging/EntityListener/PartyListener.php
- src/Repository/LogEntryRepository.php
- src/Service/LogEntryHelper.php
- src/Twig/TwigExtension.php
- templates/case/log.html.twig
- templates/case/log_entry_show.html.twig
- translations/log+intl-icu.da.xlf
https://jira.itkdev.dk/browse/TVIST1-252
Adds display of log entries.
> TVIST1-252: Log entry view

- docs/TRANSLATIONS.md
- templates/case/_address.html.twig
- templates/search/index.html.twig
- translations/EasyAdminBundle+intl-icu.en.xlf
- translations/address+intl-icu.en.xlf
- translations/admin+intl-icu.en.xlf
- translations/agenda+intl-icu.en.xlf
- translations/agenda_status+intl-icu.en.xlf
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
- translations/common+intl-icu.en.xlf
- translations/dashboard+intl-icu.en.xlf
- translations/documents+intl-icu.en.xlf
- translations/log+intl-icu.en.xlf
- translations/login+intl-icu.en.xlf
- translations/messages+intl-icu.en.xlf
- translations/navbar+intl-icu.en.xlf
- translations/notes+intl-icu.en.xlf
- translations/party+intl-icu.en.xlf
- translations/reminder+intl-icu.en.xlf
- translations/search+intl-icu.da.xlf
- translations/search+intl-icu.en.xlf
- translations/security.en.xlf
- translations/sidebar+intl-icu.en.xlf
- translations/validators.en.xlf
https://jira.itkdev.dk/browse/TVIST1-481
Fixes issues with placeholders in translation messages.
> TVIST1-481: Translations

- src/Controller/CaseController.php
- src/Form/CaseMoveType.php
- src/Repository/BoardRepository.php
- templates/case/_move_case.html.twig
- templates/case/summary.html.twig
- translations/case+intl-icu.da.xlf
* Added logic for moving case from one board to another
https://jira.itkdev.dk/browse/TVIST1-451
> TVIST1-451: Allow switch between suitable boards

- .env
- config/packages/framework.yaml
* Added configuration of trusted proxies via local environment
https://jira.itkdev.dk/browse/TVIST1-482
> TVIST1-482: Added configuration of trusted proxies via local environment

- README.md
- assets/app.js
- package.json
- src/Form/DocumentType.php
- templates/documents/create.html.twig
- yarn.lock
https://jira.itkdev.dk/browse/TVIST1-504
> TVIST1-504: Clean up document create form

- src/Security/AzureAdLoginAuthenticator.php
> TVIST1: Use correct method for getting claims

- src/Controller/Admin/BoardCrudController.php
- src/Controller/Admin/UserCrudController.php
- src/Controller/DocumentController.php
- templates/admin/mail-template/detail.html.twig
- templates/case/hearing/index.html.twig
- templates/documents/index.html.twig
- templates/translations/admin.html.twig
- translations/admin+intl-icu.en.xlf
- translations/admin.da.xlf
- translations/agenda+intl-icu.da.xlf
- translations/agenda+intl-icu.en.xlf
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
- translations/common+intl-icu.da.xlf
- translations/dashboard+intl-icu.da.xlf
- translations/documents+intl-icu.da.xlf
- translations/documents+intl-icu.en.xlf
- translations/mail_template+intl-icu.da.xlf
- translations/mail_template+intl-icu.en.xlf
- translations/messages+intl-icu.da.xlf
- translations/messages+intl-icu.en.xlf
- translations/notes+intl-icu.da.xlf
- translations/party+intl-icu.da.xlf
- translations/reminder+intl-icu.da.xlf
- translations/reminder+intl-icu.en.xlf
- translations/security.da.xlf
- translations/sidebar+intl-icu.da.xlf
- translations/validators.da.xlf
https://jira.itkdev.dk/browse/TVIST1-506
Updates and cleans up translations.
> TVIST1-506: Translations

- assets/hearing/edit_post.js
- assets/hearing/edit_post.scss
- migrations/Version20220216151318.php
- migrations/Version20220217141520.php
- migrations/Version20220221084820.php
- migrations/Version20220221113122.php
- src/Controller/HearingController.php
- src/Entity/DigitalPost.php
- src/Entity/HearingPost.php
- src/Entity/HearingPostAttachment.php
- src/Form/HearingPostAttachmentType.php
- src/Form/HearingPostType.php
- src/Repository/HearingPostAttachmentRepository.php
- src/Service/DocumentUploader.php
- templates/case/hearing/_form.html.twig
- templates/case/hearing/index.html.twig
- templates/case/hearing/post_create.html.twig
- templates/case/hearing/post_edit.html.twig
- templates/case/hearing/post_show.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
- webpack.config.js
https://jira.itkdev.dk/browse/TVIST1-484
Adds ordered attachments to hearing posts.
> TVIST1-484: Added hearing post attachments

- src/Controller/SidebarController.php
> TVIST1: Update active submenus

- templates/case/decision/create.html.twig
* Adds grouping of recipients during creation of decisions.
> TVIST1: Preliminary grouping of recipients

- templates/dashboard/index.html.twig
Hides inactive cases till further information regarding when cases are considered inactive.
> TVIST1: Hide inactive cases

- src/Controller/CaseController.php
- src/Service/AddressHelper.php
- src/Service/BBRHelper.php
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
https://jira.itkdev.dk/browse/TVIST1-517
> TVIST1-517: Translated and displayed messages

- README.md
Adds cron job section to README
> TVIST1: Add cron jobs to README

- README.md
> TVIST1: Update cronjob readme

- src/Controller/CaseController.php
- templates/case/summary.html.twig
* Displays recent communication on case summary page
We could consider making the number of shown items configurable.
> TVIST1-518: Show latest communication on summary

- assets/case/new.js
- src/Controller/CaseController.php
- src/Form/CaseEntityType.php
* Preselects municipality in case creation form
> TVIST1-518: Preselect municipality when creating case

- src/Controller/CaseProgressController.php
* Updates progress bar displaying status to be more telling
> TVIST1-518-update-case-status-progress-bar

- config/services.yaml
- src/Entity/Hearing.php
- src/Entity/HearingPost.php
- src/Entity/MailTemplate.php
- src/Service/MailTemplateHelper.php
- templates/translations/mail_template.html.twig
- translations/mail_template+intl-icu.da.xlf
- translations/mail_template+intl-icu.en.xlf
* General update of mail templates
* Translation of mail template types
> TVIST1-518: Update mail templates

- composer.lock
- src/Service/BBRHelper.php
- templates/case/_case_show/_resident_and_rent_board_shareds.html.twig
https://jira.itkdev.dk/browse/TVIST1-517
- TVIST1-517: BBR fixes
- TVIST1-517: Handled BBR meddelelsesurl
> TVIST1-517: BBR fixes

- src/Entity/Embeddable/Address.php
* Fixes bug where changing from address with floor or side to one without would cause errors
> TVIST1-518: Update setters for side and floor to allow null

- src/Controller/SearchController.php
* Updated search for case number to accept parts of case number
> TVIST1-518: Allow search for parts of case number

- src/Form/AgendaCaseItemNewType.php
- src/Service/BoardHelper.php
* Allow adding cases from suitable boards to agendas
> TVIST1-518: Allow adding cases from suitable boards to agendas

- src/Controller/DocumentController.php
- src/Form/DocumentType.php
- templates/documents/create.html.twig
- translations/documents+intl-icu.da.xlf
- translations/documents+intl-icu.en.xlf
> TVIST1-518: Handled multiple files in document upload

- src/Controller/AgendaManuelItemDocumentController.php
- templates/agenda_manuel_item/document_upload.html.twig
* Fixes issue with uploading document on manuel agenda item
> TVIST1-518: Allow upload of documents on manuel agenda items

- src/Repository/BoardMemberRepository.php
* Fixes issue where board members who has roles on separate boards would display twice
> TVIST1-518: Fix issue with some boardmembers displaying twice

- templates/agenda/index.html.twig
- templates/agenda_case_item/documents.html.twig
- templates/agenda_case_item/documents_attach.html.twig
- templates/agenda_manuel_item/documents.html.twig
- templates/case/_case_show/_resident_and_rent_board_shareds.html.twig
- templates/case/_case_show/fence_review_case.html.twig
- templates/case/index.html.twig
- templates/dashboard/_unassigned_cases.html.twig
- templates/documents/index.html.twig
- templates/notes/index.html.twig
- templates/reminder/index.html.twig
- templates/search/index.html.twig
* Adds space in between buttons by avoiding the use of `btn-group`
> TVIST1-518: Avoided grouping buttons

- src/Command/DigitalPostSendCommand.php
https://jira.itkdev.dk/browse/TVIST1-27
Uses document name as attachment name.
> TVIST1-27: Fixed attachment names

- src/Controller/Admin/BoardCrudController.php
- src/Controller/Admin/BoardMemberCrudController.php
- src/Controller/Admin/BoardRoleCrudController.php
- src/Controller/Admin/ComplaintCategoryCrudController.php
- src/Controller/Admin/UserCrudController.php
- src/Controller/AgendaController.php
- src/Controller/CaseController.php
- src/Controller/DefaultController.php
- src/Form/CaseEntityType.php
- src/Form/FenceReviewCaseType.php
- src/Form/RentBoardCaseType.php
- src/Form/ResidentComplaintBoardCaseType.php
- src/Repository/BoardMemberRepository.php
- src/Service/PartyHelper.php
* Orders choices in forms alphabetically
> TVIST1-518: Ordered choice types alphabetically

- .editorconfig
- assets/_dashboard.scss
- assets/app.scss
- templates/dashboard/_grid_information.html.twig
- Aligned grid headers
- Aligned grid rows
- Cleaned up and applied coding standards
> Grid alignment

- src/Controller/DocumentController.php
- src/Form/DocumentType.php
- templates/documents/edit.html.twig
- templates/documents/index.html.twig
- translations/documents+intl-icu.da.xlf
- translations/documents+intl-icu.en.xlf
Allows editing documents (name and type only).
> Added editing of documents

- templates/case/status.html.twig
* Resolves date issue
* Hides deadline that awaits further implementation
> TVIST1-518: Deadline date diff error fix

- assets/case/edit.js
- assets/case/new.js
- assets/dawa-address-lookup.js
- src/Form/RentBoardCaseType.php
- src/Form/ResidentComplaintBoardCaseType.php
- templates/case/edit.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
- webpack.config.js
* Adds button for copying address in relevant cases
> TVIST1-518: Copy address functionality during create and edit cases

- fixtures/complaint_category.yaml
- migrations/Version20220316134557.php
- migrations/Version20220323140325.php
- src/Controller/Admin/ComplaintCategoryCrudController.php
- src/Entity/Board.php
- src/Entity/ComplaintCategory.php
* Allows multiple `Board`s per `ComplaintCategory`
* Removes unnecessary relation between `ComplaintCategory` and `Municipality`
> TVIST1-518: Allowed multiple boards per complaint category

- src/Controller/Admin/UserCrudController.php
* Removes ability to search in `UserCrudController`
* Denies access to `UserCrudController` index page
> Disable search bar in UserCrudController

- templates/case/show.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
* Updates button to display 'Opret part' rather than 'Opret repræsentant'.
> Reworded button text

- docker-compose.server.yml
- docker-compose.yml
- Allowed uploading very large files
- Fixed indentation
> Server settings

- migrations/Version20220324140727.php
- src/Entity/CaseEntity.php
- src/Form/FenceReviewCaseType.php
- src/Form/RentBoardCaseType.php
- src/Form/ResidentComplaintBoardCaseType.php
- templates/case/_case_show/_resident_and_rent_board_shareds.html.twig
- templates/case/_case_show/fence_review_case.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
* Adds property for extra complaint category information to cases
> TVIST1-518: Add extra complaint category information property to cases

- migrations/Version20220324150428.php
- src/Entity/Agenda.php
- src/Entity/RentBoardCase.php
- src/Entity/ResidentComplaintBoardCase.php
- src/Form/RentBoardCaseType.php
- src/Form/ResidentComplaintBoardCaseType.php
- src/Twig/TwigExtension.php
- templates/agenda/index.html.twig
- templates/case/_case_show/_lease_information/rent_board_case.html.twig
- templates/case/_case_show/_lease_information/resident_complaint_board_case.html.twig
- templates/case/_case_show/_resident_and_rent_board_shareds.html.twig
- templates/sidebar/agenda-sidebar.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
* Added `leaseRegulatedAt` property to `RentBoardCase` and `ResidentComplaintBoardCase`
* Updated some templates where `null` dates would show current date
> TVIST1-518: Added regulatedAt property to some cases

- src/Command/CPRLookupCommand.php
- src/Command/CVRLookupCommand.php
- Added CPR lookup command
- Fixed typo and cleaned up
> CPR lookup

- templates/form/theme.html.twig
https://symfony.com/doc/5.4/form/form_customization.html
> Fixed form theme

- src/Form/AgendaCaseItemNewType.php
- src/Repository/CaseEntityRepository.php
* Fixes exception caused by calling removed/updated method
> TVIST1: Allow creation of AgendaCaseItems

- src/Repository/CaseEntityRepository.php
* Handles empty list behaving different than (i) expected
> Handle empty list during collection of cases that are ready for agenda

- composer.lock
- fixtures/digital_post.yml
- src/Command/DigitalPostSendCommand.php
- src/Service/DigitalPostHelper.php
https://jira.itkdev.dk/browse/TVIST1-27
Handles sending digital post to a CVR number.
> TVIST1-27: Handled CVR digital post

- src/Controller/Admin/BoardCrudController.php
- src/Controller/Admin/BoardMemberCrudController.php
- src/Controller/Admin/BoardRoleCrudController.php
- src/Controller/Admin/ComplaintCategoryCrudController.php
- src/Controller/Admin/MailTemplateCrudController.php
- src/Controller/Admin/MunicipalityCrudController.php
- src/Controller/Admin/PartyCrudController.php
- translations/admin+intl-icu.en.xlf
- translations/admin.da.xlf
* Handles exception thrown during deletion of entities in EasyAdmin
> TVIST1: Display flash when delete results in exception in admin

- src/Command/DigitalPostListCommand.php
- src/Entity/DigitalPost.php
- src/Entity/DigitalPost/Recipient.php
- templates/case/communication/digital_post/index.html.twig
https://jira.itkdev.dk/browse/TVIST1-432
- TVIST1-432: Added Digital post list command
- TVIST1-432: Fixed colspan
> TVIST1-432: Digital post list

- src/Service/DocumentUploader.php
* Uses `StreamedResponse` for download documents
> TVIST1: Stream document download

- src/Service/DocumentUploader.php
* Fixes issue where `document_view` doesn't display correctly
> TVIST1: Ensure documents are viewable

- src/Controller/DecisionController.php
- templates/case/decision/index.html.twig
- translations/decision+intl-icu.da.xlf
- translations/decision+intl-icu.en.xlf
* Ensures case has at least one party before allowing creation of decision
> TVIST1: Add check for case having party before creating decision

- fixtures/digital_post.yml
- src/Command/DigitalPostListCommand.php
- src/Command/DigitalPostSendCommand.php
- src/Entity/DigitalPost.php
https://jira.itkdev.dk/browse/TVIST1-533
> Handle max number of retries for sending digital post)

- src/Controller/AgendaController.php
* Sorts board members that are assigned to agendas
> TVIST1: Sort board members on agenda

- assets/admin/board_member_cpr_lookup.js
- assets/admin/party_identifier_lookup.js
- src/Controller/Admin/BoardMemberCrudController.php
- src/Controller/Admin/PartyCrudController.php
- src/EventSubscriber/EasyAdminSubscriber.php
- templates/admin/field/board_member_cpr_lookup.html.twig
- templates/admin/field/party_identifier_lookup.html.twig
- translations/admin+intl-icu.en.xlf
- translations/admin.da.xlf
- translations/case+intl-icu.da.xlf
- translations/validator+intl-icu.en.xlf
- webpack.config.js
* Adds lookup button to `BoardMemberCrudController`
> TVIST1-539: Update BoardMemberCrudController with lookup button

- assets/party/identifier-lookup.js
- src/Form/PartyFormType.php
- templates/party/add.html.twig
- webpack.config.js
* Add identification lookup during addition of parties to case
https://jira.itkdev.dk/browse/TVIST1-539
> TVIST1-539: Add identification lookup during addition of parties to case

- src/Form/DocumentType.php
- translations/documents+intl-icu.da.xlf
- translations/documents+intl-icu.en.xlf
* Updates allowed document mimetypes
> TVIST1: Updated allowed document mimetypes

- src/Controller/Admin/MailTemplateCrudController.php
- src/Entity/MailTemplate.php
- templates/translations/admin.html.twig
- templates/translations/validators.html.twig
- translations/admin+intl-icu.en.xlf
- translations/admin.da.xlf
- translations/validators.da.xlf
- translations/validators.en.xlf
https://jira.itkdev.dk/browse/TVIST1-435
> TVIST1-435: Added check for valid mail template mime type

- fixtures/case_entity.yaml
- migrations/Version20220506111917.php
- src/Controller/Admin/BoardMemberCrudController.php
- src/Entity/RentBoardCase.php
- src/Entity/ResidentComplaintBoardCase.php
- src/Form/RentBoardCaseType.php
- src/Form/ResidentComplaintBoardCaseType.php
- templates/case/_case_show/_resident_and_rent_board_shareds.html.twig
- translations/agenda+intl-icu.da.xlf
- translations/agenda+intl-icu.en.xlf
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
* Makes `bringerPhone` non-required
* Makes `leaseType` non-required
* Renames some property displays
* Changes `leaseRegulatedRent`
> TVIST1: Update case form types

- templates/documents/index.html.twig
* Translates document type on documents created via templates
> TVIST1: Translates document types generated via templates

- src/Controller/CaseController.php
- src/Form/CaseStatusForm.php
- templates/case/status.html.twig
* Updates display of current status 
Before
After
> TVIST1: Updated case status display

- templates/case/summary.html.twig
* Allows creation of reminders from the case `summary` page
> TVIST1: Added method for creating reminder on case summary page

- src/Controller/AgendaCaseItemController.php
- src/Controller/AgendaController.php
- src/Controller/AgendaItemController.php
- src/Controller/AgendaManuelItemDocumentController.php
- src/Controller/CaseController.php
- src/Controller/CaseReminderController.php
- src/Controller/DecisionController.php
- src/Controller/DocumentController.php
- src/Controller/HearingController.php
- src/Controller/NoteController.php
- templates/common/flash_messages.html.twig
- templates/layout-with-agenda-submenu.html.twig
- templates/layout-with-case-submenu.html.twig
- templates/layout.html.twig
- translations/agenda+intl-icu.da.xlf
- translations/agenda+intl-icu.en.xlf
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
- translations/decision+intl-icu.da.xlf
- translations/decision+intl-icu.en.xlf
- translations/documents+intl-icu.da.xlf
- translations/documents+intl-icu.en.xlf
- translations/notes+intl-icu.da.xlf
- translations/notes+intl-icu.en.xlf
https://jira.itkdev.dk/browse/TVIST1-543
Adds flash messages in controller actions.
> Add flash messages

- migrations/Version20220512104651.php
- src/Controller/CaseController.php
- src/Entity/LogEntry.php
- src/Repository/LogEntryRepository.php
https://jira.itkdev.dk/browse/TVIST1-547
Use ULIDs for log entry ids (cf. <https://symfony.com/doc/current/components/uid.html#ulids>)
> TVIST1-541: Use ULID for log entry id

- migrations/Version20220512123801.php
- src/Entity/AgendaItem.php
- src/Form/AgendaCaseItemEditType.php
- src/Form/AgendaCaseItemNewType.php
- src/Form/AgendaManuelItemType.php
- src/Service/MailTemplate/ComplexMacroHelper.php
- templates/layout-with-agenda-item-submenu.html.twig
* Makes meeting point optional on agenda items
* Allows `null` values in tables created by complex macros
* Displays flash messages on agenda item layout
https://jira.itkdev.dk/browse/TVIST1-548
> TVIST1-548: Unrequired meeting point on agenda items

- src/Controller/DocumentController.php
- src/Entity/CaseDocumentRelation.php
- src/Form/DocumentFilterType.php
- src/Repository/CaseDocumentRelationRepository.php
- src/Repository/DocumentRepository.php
- templates/documents/index.html.twig
- translations/documents+intl-icu.da.xlf
https://jira.itkdev.dk/browse/TVIST1-549
Adds filtering and sorting on the document list.
> TVIST1-549: Document list filters and sorting

- templates/agenda/show.html.twig
* Displays agenda case item title on agenda overview
https://jira.itkdev.dk/browse/TVIST1-550
> TVIST1-550: Display agenda case item title on agenda item display

- src/Form/DocumentFilterType.php
- translations/documents+intl-icu.da.xlf
- translations/documents+intl-icu.en.xlf
https://jira.itkdev.dk/browse/TVIST1-549
Adds Danish translations.
> TVIST1-549: Translations

- config/services.yaml
- src/Controller/Admin/MailTemplateController.php
- src/Controller/Admin/MailTemplateCrudController.php
- src/Entity/AgendaCaseItem.php
- src/Entity/InspectionLetter.php
- src/Repository/InspectionLetterRepository.php
- src/Service/MailTemplate/ComplexMacroHelper.php
- src/Service/MailTemplateHelper.php
- templates/admin/mail-template/detail.html.twig
- templates/translations/mail_template.html.twig
- translations/mail_template+intl-icu.da.xlf
- translations/mail_template+intl-icu.en.xlf
https://jira.itkdev.dk/browse/TVIST1-435
Also contains some typo fixes.
- TVIST1-435: Moved repository class
- TVIST1-435: Added entity selector to template preview
- TVIST1-435: Cleaned up translatable text
- TVIST1-435: Fixed typo
- TVIST1-435: Fixed typo
> TVIST1-435: Template preview improvements

- src/Form/DocumentFilterType.php
- src/Repository/AgendaCaseItemRepository.php
- src/Repository/DigitalPostAttachmentRepository.php
- src/Repository/DigitalPostRepository.php
- src/Service/DocumentDeletableHelper.php
- src/Twig/TwigExtension.php
- templates/documents/index.html.twig
- translations/documents+intl-icu.da.xlf
- translations/documents+intl-icu.en.xlf
* Adds check for whether documents may be (soft)deleted
* Translates document types used in `DocumentFilterType`
https://jira.itkdev.dk/browse/TVIST1-555
> TVIST1-555: Add checks for documents being (soft)deletable

- .github/workflows/pr.yaml
Adds Action to check that translations are up to date.
> Added translation check

- assets/case/municipality_and_board_selector.js
- assets/case/new.js
- src/Controller/CaseController.php
- src/Form/NewCaseMunicipalityAndBoardType.php
- src/Service/BoardHelper.php
- templates/case/edit.html.twig
- templates/case/new_prepare.html.twig
- templates/navbar/_menu.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
- webpack.config.js
* Splits case creation process into two steps
https://jira.itkdev.dk/browse/TVIST1-557
> TVIST1-557: Split case creation into two steps

- migrations/Version20220523081200.php
- src/Controller/Admin/PartyCrudController.php
- src/Entity/Embeddable/Identification.php
- src/Form/Embeddable/IdentificationType.php
- src/Form/FenceReviewCaseType.php
- src/Form/PartyFormType.php
- src/Form/RentBoardCaseType.php
- src/Form/ResidentComplaintBoardCaseType.php
- templates/case/_identifier.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
* Makes accused identification optional in `FenceCase`
https://jira.itkdev.dk/browse/TVIST1-557
> TVIST1-557: Identifcation embeddable changes

- config/services.yaml
- src/Service/MailTemplate/ComplexMacroHelper.php
- src/Service/MailTemplateHelper.php
https://jira.itkdev.dk/browse/TVIST1-564
> TVIST1-564: Fixed handling of hyperlinks in templates

- src/Entity/AgendaBroadcast.php
- src/Entity/AgendaCaseItem.php
- src/Entity/AgendaItem.php
- src/Entity/HearingPost.php
https://jira.itkdev.dk/browse/TVIST1-563
Improves __toString() implementations. They can probably be improved even more …
> TVIST1-563: Added and updated toString implementations

- src/Controller/Admin/MailTemplateCrudController.php
- src/Service/MailTemplateHelper.php
- templates/admin/mail-template/form.html.twig
- translations/mail_template+intl-icu.da.xlf
- translations/mail_template+intl-icu.en.xlf
https://jira.itkdev.dk/browse/TVIST1-570
Another stab at making hyperlinks in mail templates behave …
> TVIST1-570: Added pragmatic solution to make hyperlinks work in mail templates

- fixtures/document.yml
Updates document fixtures according to previous changes.
> TVIST1: Updated document fixtures

- .env
- src/Service/MailTemplateHelper.php
- TVIST1-574: Updated docker domain
- TVIST1-574: Fixed typos
> feature/TVIST1-574: Misc.

- src/Controller/AgendaBroadcastController.php
- src/Controller/HearingController.php
- src/Entity/RentBoardCase.php
- src/Entity/ResidentComplaintBoardCase.php
- src/Service/MailTemplateHelper.php
https://jira.itkdev.dk/browse/TVIST1-577
- TVIST1-577: Added more template data
- TVIST1-577: Made template data easily available
- TVIST1-577: Fixed template rendering
> TVIST1-577: Template data

- src/Service/MailTemplateHelper.php
https://jira.itkdev.dk/browse/TVIST1-578
> TVIST1-578: Handled filtered placeholders in macros

- src/Entity/CaseEntity.php
- src/Entity/ComplaintCategory.php
https://jira.itkdev.dk/browse/TVIST1-580
Makes complaint category data available for mail templates.
> TVIST1-580: Made complaint category data available for mail templates

- fixtures/case_entity.yaml
- migrations/Version20220801071602.php
- src/Entity/CaseEntity.php
- src/Form/FenceReviewCaseType.php
- src/Form/RentBoardCaseType.php
- src/Form/ResidentComplaintBoardCaseType.php
- src/Service/CaseManager.php
- templates/case/summary.html.twig
- templates/translations/case.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
Adds receivedAt (indbringelsesdato) and validatedAt (valideringsdato).
https://jira.itkdev.dk/browse/TVIST1-581
> TVIST1-581: Added receivedAt and validatedAt to cases

- assets/agenda_item/new.js
- fixtures/agenda.yaml
- fixtures/case_entity.yaml
- migrations/Version20220801105146.php
- migrations/Version20220815074005.php
- src/Controller/AgendaBroadcastController.php
- src/Controller/AgendaController.php
- src/Controller/CaseController.php
- src/Entity/Agenda.php
- src/Form/AgendaEditType.php
- src/Form/AgendaNewType.php
- src/Service/AddressHelper.php
- src/Service/MailTemplate/ComplexMacroHelper.php
- templates/agenda/create.html.twig
- templates/agenda/show.html.twig
- translations/agenda+intl-icu.da.xlf
- translations/agenda+intl-icu.en.xlf
* Added meeting point property to Agenda
* Added checks for agenda having date, start time, end time and meeting point before allowing status ready (Klar).
* Automatically fills out address meeting point on `AgendaCaseItem` if it is to be inspected.
https://jira.itkdev.dk/browse/TVIST1-588
> TVIST1-588: Agenda meeting point changes

- src/Service/DocumentUploader.php
- src/Service/OS2Forms/SubmissionNormalizers/AbstractSubmissionNormalizer.php
https://jira.itkdev.dk/browse/TVIST1-606
* Ensures temp files are unlinked
> TVIST1-606: Ensured unlinking of temp files

- migrations/Version20221003111814.php
- src/Controller/Admin/ComplaintCategoryCrudController.php
- src/Entity/ComplaintCategory.php
- templates/case/_case_show/_resident_and_rent_board_shareds.html.twig
- templates/case/_case_show/fence_review_case.html.twig
- templates/translations/admin.html.twig
- translations/admin+intl-icu.en.xlf
- translations/admin.da.xlf
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
https://jira.itkdev.dk/browse/TVIST1-638
* Adds KLE to complaint category
> TVIST1-638: Added KLE number to complaint category

- .github/workflows/pr.yaml
- CHANGELOG.md
* Updates `CHANGELOG.md`
* Adds check for change log following coding standards to our GitHub Actions
> TVIST1: Cleaned up CHANGELOG

- src/Entity/Embeddable/Address.php
* Adds address extra information placeholder for mail templates
> TVIST1: Added address extra information template placeholder

- src/Service/MailTemplateHelper.php
https://jira.itkdev.dk/browse/SUPP0RT-738
* Encodes special characters during template generation.
> SUPP0RT-738: Encoded special chars during pdf generation

- assets/case/show.js
- src/Controller/PartyController.php
- src/Form/AddPartyFromIndexType.php
- src/Form/PartyFormType.php
- templates/case/show.html.twig
- templates/party/add.html.twig
https://jira.itkdev.dk/browse/TVIST1-689
* Adds logic for preselecting party type
> TVIST1-689: Added logic to preselect party type

- src/Service/DocumentUploader.php
https://jira.itkdev.dk/browse/SUPP0RT-740
* Ensures no slash or backslashes in filename during view document action.
> SUPP0RT-740: Handled filename issues

- CHANGELOG.md
- src/Controller/HearingController.php
- src/Form/HearingFinishType.php
- templates/case/hearing/index.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
https://jira.itkdev.dk/browse/TVIST1-712
- Allows a case to enter the hearing phase without a counterpart.
> TVIST1-712: Allowed hearing on cases without a counterpart

- CHANGELOG.md
- assets/mail_templates/custom_data.js
- src/Controller/Admin/MailTemplateCrudController.php
- src/Form/MailTemplateCustomDataType.php
- src/Service/MailTemplateHelper.php
- templates/case/hearing/post_show.html.twig
- translations/admin+intl-icu.en.xlf
- translations/admin.da.xlf
https://jira.itkdev.dk/browse/TVIST1-673
* Allows configuration of mail template custom fields to either text or textArea type.
> TVIST1-673: Added types to mail template custom fields

- CHANGELOG.md
- migrations/Version20221207124626.php
- src/Entity/CaseEntity.php
- templates/case/_case_show/_resident_and_rent_board_shareds.html.twig
- templates/case/_case_show/fence_review_case.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
https://jira.itkdev.dk/browse/TVIST1-713
* Adds `onBehalfOf` property to cases which is to contain a name if case is created on behalf of someone.
Currently it cannot be used or set, but it will later when the OS2Forms data is handled.
> TVIST1-713: Added case created on behalf of information

- .docker/libreoffice-api/app/server.js
- CHANGELOG.md
https://jira.itkdev.dk/browse/TVIST1-723
- TVIST1-723: Made PDF (somewhat) accessible
- TVIST1-723: Set PDF paper size and orientation
> TVIST1-723: PDF accessibility

- src/Command/DigitalPostListCommand.php
https://jira.itkdev.dk/browse/SUPP0RT-814
> SUPP0RT-814: Added debug info

- fixtures/mail_template_macro.yaml
https://jira.itkdev.dk/browse/TVIST1-734
Updates address template macros to show how to handle punctuation and spacing before optional address parts.
> TVIST1-734: Updated address template macros

- CHANGELOG.md
- src/Controller/HearingController.php
- src/Form/HearingFinishType.php
- templates/case/hearing/index.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
https://jira.itkdev.dk/browse/TVIST1-729
* Allows hearing to start with any one part
> TVIST1-729: Allow hearing to start with any one part

- CHANGELOG.md
- assets/app.scss
- assets/hearing/delete_post.scss
- src/Controller/HearingController.php
- src/EventSubscriber/EntityPostPersistSubscriber.php
- src/Logging/EntityListener/CaseDocumentRelationListener.php
- src/Logging/EntityListener/HearingPostListener.php
- src/Service/DocumentUploader.php
- templates/case/hearing/index.html.twig
- templates/case/log.html.twig
- translations/case+intl-icu.da.xlf
- translations/case+intl-icu.en.xlf
- translations/log+intl-icu.da.xlf
- translations/log+intl-icu.en.xlf
https://jira.itkdev.dk/browse/TVIST1-725
* Allows deletion of created hearing post requests and responses
* Sends hearing post response receipt upon approval rather than creation.
> TVIST1-725: Allow deletion of hearing posts

- CHANGELOG.md
> Release 1.0.4

- CHANGELOG.md
> Release 1.0.5

- CHANGELOG.md
- composer.lock
https://jira.itkdev.dk/browse/SERV-628
* Updated `symfony/security-bundle`
> SERV-528: Updated symfony/security-bundle

- composer.lock
- symfony.lock
https://jira.itkdev.dk/browse/SERV-628
* Security updates.
> SERV-628: Security updates

- CHANGELOG.md
- src/Controller/DocumentController.php
- templates/documents/index.html.twig
https://jira.itkdev.dk/browse/TVIST1-752
* Added pagination of documents
> TVIST1-752: Added pagination of documents

- migrations/Version20230201141728.php
- src/Command/CaseDeleteCommand.php
- src/Controller/HearingController.php
- src/Entity/Document.php
- src/Logging/EntityListener/HearingPostListener.php
- src/Service/CaseManager.php
- tests/Service/CaseManagerTest.php
https://jira.itkdev.dk/browse/TVIST1-750
- TVIST1-750: Removed reference from document to hearing post
- TVIST1-750: Added case delete command [WIP]
> Case cleanup

- CHANGELOG.md
- config/packages/twig.yaml
- templates/agenda/index.html.twig
- templates/agenda/show.html.twig
- templates/agenda_case_item/inspection/index.html.twig
- templates/case/log.html.twig
- templates/case/log_entry_show.html.twig
https://jira.itkdev.dk/browse/TVIST1-778
* Showed correct time in frontend
> TVIST1-778: Showed correct time in frontend

- CHANGELOG.md
> Release 1.1.2

- CHANGELOG.md
- assets/case/identification-lookup.js
- src/Controller/CaseController.php
- src/Service/CprHelper.php
Fixes CPR lookup with updated [itk-dev/serviceplatformen](https://github.com/itk-dev/serviceplatformen/tree/feature/guzzle7-adapter).
> TVIST1-436: Data lookup

- .docker/data/.gitignore
- .docker/data/README.md
- .docker/nginx.conf
- .docker/vhost.conf
- .editorconfig
- CHANGELOG.md
- README.md
- docker-compose.dev.yml
- docker-compose.redirect.yml
- docker-compose.server.yml
- docker-compose.yml
- docs/BACKEND.md
- docs/DIGITAL_POST.md
- docs/NgDP.md
- docs/TESTING.md
- docs/TRANSLATIONS.md
https://jira.itkdev.dk/browse/TVIST1-755
- TVIST1-755: Updated docker compose setup
- TVIST1-755: Cleaned up documentation
> Docker compose setup

- CHANGELOG.md
- templates/documents/_delete.html.twig
- templates/documents/index.html.twig
https://jira.itkdev.dk/browse/TVIST1-810
* Fixed issue with first document on page being deleted no matter which one was selected for deletion.
> TVIST1-810: Deleted correct documents

- CHANGELOG.md
- src/Command/DigitalPostEnvelopeListCommand.php
- src/Service/SF1601/DigitalPoster.php
> Release 1.3.2

- CHANGELOG.md
- src/Service/SF1601/ForsendelseHelper.php
https://jira.itkdev.dk/browse/TVIST1-817
Sets PostKategoriKode (cf. <https://digitaliseringskataloget.srvitkhulk.itkdev.dk/digitaliseringskataloget.dk/sf1601/SF1601%20Bilag%2020211025/SF1601%20Postkomponent%20-%20KombiPostAfsend%20-%20Feltbeskrivelse.pdf#page=15>).
> TVIST1-817: Set post-kategori-kode

- CHANGELOG.md
- src/Controller/PartyController.php
- src/Exception/PartyException.php
https://jira.itkdev.dk/browse/TVIST1-822
* Preselects party relation type on edit.
> TVIST1-822: Preselect party type on edit

- .env
- CHANGELOG.md
- config/packages/messenger.yaml
- config/packages/twig.yaml
- config/services.yaml
- fixtures/digital_post.yml
- src/Command/DigitalPostEnvelopeListCommand.php
- src/Controller/Admin/DashboardController.php
- src/Controller/Admin/DigitalPostEnvelopeCrudController.php
- src/Entity/DigitalPostEnvelope.php
- src/EventSubscriber/DigitalPostMessengerEventSubscriber.php
- src/Retry/DigitalPostRetryStrategy.php
- src/Service/DigitalPostEnvelopeHelper.php
- templates/admin/field/digital_post_envelope/digital_post/show.html.twig
- templates/case/communication/digital_post/_digital_post_envelope.html.twig
- templates/translations/admin.html.twig
- translations/admin+intl-icu.da.xlf
- translations/admin+intl-icu.en.xlf
- translations/digital_post+intl-icu.da.xlf
- translations/digital_post+intl-icu.en.xlf
https://jira.itkdev.dk/browse/TVIST1-837
* Adds `digital_post` message transport
* Adds digital post retry strategy
* Handles too many retries
* Updates digital post envelope template
* Adds admin view of digital post envelopes
> TVIST1-837: Added digital_post message transport

- CHANGELOG.md
- src/Command/DigitalPostEnvelopeListCommand.php
- src/Controller/AgendaBroadcastController.php
- templates/agenda/broadcast/show.html.twig
- templates/case/communication/digital_post/show.html.twig
https://jira.itkdev.dk/browse/TVIST1-817
- TVIST1-817: Handled agendas in digital post envelope list
- TVIST1-817: Updated broadcast digital post display
> TVIST-817: Digital post display

- docs/NgDP.md
https://jira.itkdev.dk/browse/TVIST1-837
> TVIST1-837: Updated documentation

- CHANGELOG.md
> Release 1.5.1

- CHANGELOG.md
- src/Service/BBRHelper.php
https://jira.itkdev.dk/browse/SUPP0RT-1129
* Updates BBR meddelelse url
> SUPP0RT-1129: Update BBR meddelelse url

- CHANGELOG.md
https://jira.itkdev.dk/browse/SUPP0RT-1129
Prepares release 1.5.2
> Release 1.5.2

- CHANGELOG.md
- README.md
- docker-compose.override.yml
https://jira.itkdev.dk/browse/SERV-699
* Adds `test` service profile to mock idps
> SERV-699: Added test service profile to mock idps

- CHANGELOG.md
- translations/agenda+intl-icu.da.xlf
- translations/digital_post+intl-icu.da.xlf
- translations/mail_template+intl-icu.da.xlf
- translations/sidebar+intl-icu.da.xlf
https://leantime.itkdev.dk/#/tickets/showTicket/1231
* Updates the spelling of "publisering" to "publicering"
> #1231: Updated translations

- CHANGELOG.md
- src/Controller/Admin/BoardRoleCrudController.php
https://leantime.itkdev.dk/#/tickets/showTicket/1232
* Fixes BoardRole crud search property
> #1232: Fixed BoardRoleCrud search property

- CHANGELOG.md
https://leantime.itkdev.dk/#/tickets/showTicket/1277
Release 1.5.5
> Release 1.5.5

- CHANGELOG.md
> Release 1.5.6

- CHANGELOG.md
- src/Command/DigitalPostEnvelopeListCommand.php
https://leantime.itkdev.dk/#/tickets/showTicket/1826
* Adds extra option to `tvist1:digital-post-envelope:list`
> 1826: Add option to digital post envelope list command

- .github/workflows/pr.yaml
- .github/workflows/release.yaml
- CHANGELOG.md
* Updates GitHub workflow images
> Update GitHub workflows runner images
